services:
  drizzle-studio:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 4983:4983
    environment:
      DATABASE_URL: postgresql://postgres:postgres@pg:5432/postgres
      DATABASE_DIRECT_URL: postgresql://postgres:postgres@pg:5432/postgres
    depends_on:
      pg:
        condition: service_healthy
    restart: always
    command: npx drizzle-kit studio --host=0.0.0.0 --port 4983
  pg:
    image: postgres:16
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
